#!/usr/bin/env bash
#
# Deploy HomeRig to your Umbrel server.
#
# Usage:
#   ./scripts/deploy-umbrel.sh                 # uses defaults
#   UMBREL_HOST=umbrel.local ./scripts/deploy-umbrel.sh
#   UMBREL_USER=umbrel UMBREL_PATH=/home/umbrel/homerig ./scripts/deploy-umbrel.sh
#
# What it does:
#   1. Rsync source code to the Umbrel (excluding node_modules, .next, etc.)
#   2. Rsync local data/ + .env.local (renamed to .env) so existing config
#      and the encryption key survive
#   3. SSH in, run `docker compose up -d --build`
#   4. Tail the first few lines of logs so you can confirm it started cleanly
#
# After deploy: http://${UMBREL_HOST}:3000

set -euo pipefail

UMBREL_HOST="${UMBREL_HOST:-umbrel.local}"
UMBREL_USER="${UMBREL_USER:-umbrel}"
UMBREL_PATH="${UMBREL_PATH:-/home/umbrel/homerig}"
LOCAL_DIR="$(cd "$(dirname "$0")/.." && pwd)"

echo "→ Deploying HomeRig"
echo "   from: ${LOCAL_DIR}"
echo "     to: ${UMBREL_USER}@${UMBREL_HOST}:${UMBREL_PATH}"
echo

# Sanity: make sure the local env file exists (it carries the encryption key)
if [[ ! -f "${LOCAL_DIR}/.env.local" ]]; then
  echo "✗ ${LOCAL_DIR}/.env.local not found. Create it with HOMERIG_ENCRYPTION_KEY set." >&2
  echo "  See .env.local.example." >&2
  exit 1
fi
if ! grep -q "^HOMERIG_ENCRYPTION_KEY=" "${LOCAL_DIR}/.env.local"; then
  echo "✗ ${LOCAL_DIR}/.env.local is missing HOMERIG_ENCRYPTION_KEY." >&2
  exit 1
fi

# Verify host reachable
if ! ssh -o ConnectTimeout=5 -o BatchMode=yes "${UMBREL_USER}@${UMBREL_HOST}" 'echo ok' >/dev/null 2>&1; then
  echo "✗ Can't SSH to ${UMBREL_USER}@${UMBREL_HOST}." >&2
  echo "  Check: ssh ${UMBREL_USER}@${UMBREL_HOST}  works interactively first." >&2
  exit 1
fi

# Create remote dir
ssh "${UMBREL_USER}@${UMBREL_HOST}" "mkdir -p ${UMBREL_PATH}/data"

# Rsync the source. We're deliberate about excludes: anything that's huge,
# regenerated by the build, or environment-specific stays local.
echo "→ Syncing source code..."
rsync -avz --delete \
  --exclude '.git' \
  --exclude 'node_modules' \
  --exclude '.next' \
  --exclude 'data' \
  --exclude '.env.local' \
  --exclude 'homerig-stock.archive' \
  --exclude '.DS_Store' \
  --exclude '*.log' \
  "${LOCAL_DIR}/" "${UMBREL_USER}@${UMBREL_HOST}:${UMBREL_PATH}/"

# Sync the database. CRITICAL: use --ignore-existing so we only seed the DB on
# the *first* deploy. Subsequent deploys preserve whatever's on the Umbrel
# (settings the user changed via the dashboard, the URL fix that has to differ
# between Mac and Umbrel for network reasons, etc.).
#
# To force-push the local DB later (e.g. you really did make schema changes
# you can't migrate cleanly), pass FORCE_DB_PUSH=1.
if [[ -f "${LOCAL_DIR}/data/homerig.db" ]]; then
  if [[ "${FORCE_DB_PUSH:-0}" == "1" ]]; then
    echo "→ FORCE_DB_PUSH=1 — overwriting remote DB with local copy..."
    rsync -avz "${LOCAL_DIR}/data/" "${UMBREL_USER}@${UMBREL_HOST}:${UMBREL_PATH}/data/"
  else
    echo "→ Seeding remote data/ (only files that don't exist remotely)..."
    rsync -avz --ignore-existing "${LOCAL_DIR}/data/" "${UMBREL_USER}@${UMBREL_HOST}:${UMBREL_PATH}/data/"
  fi
fi

# Translate .env.local → .env on the remote.
# docker-compose's `env_file:` reads .env automatically; .env.local is a
# Next.js dev convention that's not honored by Docker.
echo "→ Syncing encryption key (.env.local → remote .env)..."
scp "${LOCAL_DIR}/.env.local" "${UMBREL_USER}@${UMBREL_HOST}:${UMBREL_PATH}/.env" >/dev/null
ssh "${UMBREL_USER}@${UMBREL_HOST}" "chmod 600 ${UMBREL_PATH}/.env"

# Build + (re)start the container. We use --build so changes pick up.
echo "→ Building & starting container on Umbrel..."
ssh "${UMBREL_USER}@${UMBREL_HOST}" "cd ${UMBREL_PATH} && docker compose up -d --build"

# Brief log peek
echo
echo "→ First 30 log lines:"
ssh "${UMBREL_USER}@${UMBREL_HOST}" "cd ${UMBREL_PATH} && docker compose logs --tail 30 homerig"

echo
echo "✓ Done. Open: http://${UMBREL_HOST}:3000"
echo "  Follow logs: ssh ${UMBREL_USER}@${UMBREL_HOST} 'cd ${UMBREL_PATH} && docker compose logs -f'"
